### ISSUE TITLE
Getting a "530 Login incorrect" when trying to use it

### ISSUE THREAD

**Issue by proper1g1r** [kosmosnautti/dltool#1]
Thanks a lot for open sourcing this work in the first place! ❤️ 

I'm on macOS Venture 13.5 with an M2 Max, running Python 3.11.7. This is the output I'm getting:

```
2024-02-16 10:24:24 | Opening input DAT-file...
2024-02-16 10:24:24 | Processing No-Intro: Nintendo - Nintendo DS (Encrypted)...
2024-02-16 10:24:25 | Connecting to Myrient FTP-server...
Traceback (most recent call last):
  File "/Users/fred/Repositories/dltool/dltool.py", line 138, in <module>
    ftp.login()
  File "/opt/homebrew/Cellar/python@3.11/3.11.7_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ftplib.py", line 414, in login
    resp = self.sendcmd('PASS ' + passwd)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.7_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ftplib.py", line 281, in sendcmd
    return self.getresp()
           ^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.7_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ftplib.py", line 254, in getresp
    raise error_perm(resp)
ftplib.error_perm: 530 Login incorrect.
```

Is there anything I could try on my end? Or is this something on Myrient's end?

**Comment by kosmosnautti** [comment]
Have not used this myself in a while, but according to Myrient's Telegram-channel (https://t.me/s/myrient) it seems that there has been some problems on their end starting around the end of last year. Also, according to the last message over there the FTP-server seems to be down for maintenance at the moment.

I'll still leave this open in case they change something in their end (hopefully not) that breaks this script while getting their FTP-server back up and running.
