### ISSUE TITLE
 Bad IP connecting

### ISSUE THREAD

**Issue by pirsir76** [kosmosnautti/dltool#3]
Seems not to connect to Myrient.

Here is the output:
D:\Chrome Downloads\dltool-main>python3 dltool.py -i romset.dat -o /
2024-04-09 22:07:26 | ←[92mOpening input DAT-file...←[00m
2024-04-09 22:07:26 | ←[92mProcessing Redump: Sony - PlayStation...←[00m
2024-04-09 22:07:26 | ←[92mConnecting to Myrient FTP-server...←[00m
Traceback (most recent call last):
  File "D:\Chrome Downloads\dltool-main\dltool.py", line 141, in <module>
    maindir = ftp.nlst()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\ftplib.py", line 553, in nlst
    self.retrlines(cmd, files.append)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\ftplib.py", line 462, in retrlines
    with self.transfercmd(cmd) as conn, \
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\ftplib.py", line 393, in transfercmd
    return self.ntransfercmd(cmd, rest)[0]
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\ftplib.py", line 359, in ntransfercmd
    resp = self.sendcmd(cmd)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\ftplib.py", line 281, in sendcmd
    return self.getresp()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\ftplib.py", line 252, in getresp
    raise error_temp(resp)
ftplib.error_temp: 425 Security: Bad IP connecting.

**Comment by pirsir76** [comment]
Also, a request for a GUI would be very helpful.

**Comment by kosmosnautti** [comment]
Sorry for the late reply. That's an error from server (Myrient) side, so there's nothing I can do about that.

Regarding a GUI, I don't really use this any more myself so there will be no GUI (unless someone else will build one).
