### ISSUE TITLE
Progress bar problem (happens usually when resuming after failed download)

### ISSUE THREAD

**Issue by egyptiangio** [kosmosnautti/dltool#6]
Getting this error with annoying frequency, makes the tool virtually unusable. Seems to happen mostly when resuming a previously failed download:

raceback (most recent call last):
  File "/home/dltool/dltool.py", line 279, in <module>
    pbar += len(data)
  File "/usr/local/lib/python3.9/dist-packages/progressbar/bar.py", line 875, in __iadd__
    return self.increment(value)
  File "/usr/local/lib/python3.9/dist-packages/progressbar/bar.py", line 878, in increment
    self.update(self.value + value, *args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/progressbar/bar.py", line 925, in update
    raise ValueError(
ValueError: Value 716586472 is too large. Should be between 0 and 716585410

**Comment by aderumier** [comment]
Hi, 

I have exactly same problem when resuming previous download. It's random.

```
2024-06-20 22:07:14 | Already DLd 681/968: Pokemon Y (Europe) (En,Ja,Fr,De,Es,It,Ko)
2024-06-20 22:07:26 | Downloaded  682/968: Pom Pom Purin - Corocoro Daibouken (Japan)
2024-06-20 22:07:26 | Resuming    683/968: Poochy & Yoshi's Woolly World (Europe) (En,Fr,De,Es,It,Nl)                                        
 99% | 942.4 MiB / 942.9 MiB |################################################################################ | ETA:   0:00:00 |  11.5 MiB/sTraceback (most recent call last):
  File "dltool.py", line 279, in <module>
    pbar += len(data)
  File ".local/lib/python3.12/site-packages/progressbar/bar.py", line 875, in __iadd__
    return self.increment(value)
           ^^^^^^^^^^^^^^^^^^^^^
  File ".local/lib/python3.12/site-packages/progressbar/bar.py", line 878, in increment
    self.update(self.value + value, *args, **kwargs)
  File ".local/lib/python3.12/site-packages/progressbar/bar.py", line 925, in update
    raise ValueError(
ValueError: Value 988695691 is too large. Should be between 0 and 988695099
```
